name: Release

on:
  push:
    tags: ["v*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Create release"
      run: |
        set -x
        mkdir co2clock
        mv appinfo js lib co2clock
        tar -caf co2clock.tar.gz co2clock
        tag_name="${GITHUB_REF##*/}"
        gh release create --notes-from-tag "$tag_name"
        gh release upload "$tag_name" co2clock.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

